name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.17.3
        
    - name: Run tests
      run: go test $GITHUB_WORKSPACE/cmd/
    
    - name: Build the Docker image
      run: docker build . --file $GITHUB_WORKSPACE/build/Dockerfile --tag my-image-name:$(date +%s)
